---
version: 3
images:
  base_image:
    name: registry.fedoraproject.org/fedora:41

dependencies:
  system:
  - python3-devel
  python_interpreter:
    package_system: python313
    python_path: /usr/bin/python3.13
  ansible_core:
    package_pip: ansible-core<2.17.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt