---
- hosts: all
  become: true
  tasks:
    - name: "Add tech user"
      ansible.builtin.user:
        name: "tech"
        shell: /bin/bash
        password: "{{ tech_password }}"
        update_password: "on_create"
        group: admin
