---
- name: Push config
  hosts: auto-provision
  gather_facts: no
  connection: local
  collections:
     - juniper.device

  tasks:
    - name: Load conf. Confirm within 10 min. Wait 6 secs between chk and commit
      config:
        host: "{{ mgmt_v4_addr }}"
        user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        passwd: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        load: 'override'
        format: 'text'
        url: "{{ gondul_url }}/api/templates/magic.conf?switch={{sysname}}"
        timeout: 240
        confirm: 10
        check_commit_wait: 6
      register: response

    - name: Print the complete response
      debug:
        var: response.diff_lines

    - name: Confirm the previous commit with a commit check (but no commit)
      config:
        host: "{{ mgmt_v4_addr }}"
        user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        passwd: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        check: true
        diff: false
        commit: false
        timeout: 120
      register: response

