---
- name: Check system snapshot slice alternate
  hosts: auto-provision
  gather_facts: no
  strategy: free
  connection: local
  collections:
     - juniper.device

  tasks:
    # - name: Check snapshot state
    #   rpc:
    #     host: "{{ mgmt_v4_addr }}"
    #     user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
    #     passwd: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
    #     rpcs: 
    #       - "get-snapshot-information"
    #     kwargs: "media=internal"
    #     formats: "xml"
    #   register: response

    - name: Check snapshot state
      command:
        host: "{{ mgmt_v4_addr }}"
        user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        passwd: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        commands: "show system snapshot local media internal"
        timeout: 1500
        formats:
          - "json"
      register: response
      
    - name: Execute request system snapshot slice alternate
      when: response.parsed_output["snapshot-information"]["software-version"].0.package.1["package-version"] != response.parsed_output["snapshot-information"]["software-version"].1.package.1["package-version"]
      command:
        host: "{{ mgmt_v4_addr }}"
        user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        passwd: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        commands: "request system snapshot slice alternate"
        timeout: 2000