name: Build
on:
  push:
    branches: [main, master]
    paths:
      - 'junos-ee/**'
      - 'avd-ee/**'
      - '.github/workflows/build-ee.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install ansible-builder
        run: python3 -m pip install ansible-builder
      - name: Build avd-ee image
        working-directory: ./avd-ee
        run: |
          ansible-builder build --container-runtime docker -v 3 --tag ghcr.io/${{ github.repository }}-avd-ee:latest
          docker push ghcr.io/${{ github.repository }}-avd-ee:latest
