name: Build
on:
  push:
    branches: [main, master, tg23-junos]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tags
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository }}"
          echo "TAGS=$IMAGE_ID-junos-ee:latest" >> "$GITHUB_ENV"
      - name: Build junos-ee image
        uses: docker/build-push-action@v4
        with:
          context: junos-ee
          file: junos-ee/Containerfile
          push: true
          tags: ${{ env.TAGS }}
          platforms: linux/amd64
